### ISSUE TITLE
undefined is not a function (evaluating 'addListener'

### ISSUE THREAD

**Issue by rasselll** [Qolzam/react-mobile-social#1]
error on build as title suggest

**Comment by Qolzam** [comment]
Thanks for reporting! Can you give more information ?

**Comment by SNetwork** [comment]
Same issue.
<img width="383" alt="screen shot 2018-04-11 at 15 09 30" src="https://user-images.githubusercontent.com/38154986/38616366-80f06754-3d9c-11e8-8903-9583cbba6a39.png">

**Comment by indokely** [comment]
Hey,

I am also getting same error...Please have a look to attached image.

![bg-white1](https://user-images.githubusercontent.com/4360793/39096094-ddfc5a5a-4668-11e8-8157-fa33422ff91e.png)

**Comment by Qolzam** [comment]
Thank you for reporting. Excuse me for late answer. Please use `yarn` command instead of `npm install` to install `node_module` packages. Let me know if you any issue. Thanks!

**Comment by Qolzam** [comment]
Seems there is no issue with new updates. I'm going to close this issue. If you have any feel free to reopen.
